# Assignment 07 - Pandas

1) Create a DataFrame from a dictionary with columns Name, Age, City and Salary for 6 employees. Print the first 3 rows, the shape, the column names and the data types.

In [1]:
import pandas as pd

# Create a DataFrame for 6 employees
df = pd.DataFrame({
    "Name": ["Ayesha", "Bilal", "Chen", "Deepa", "Ethan", "Farah"],
    "Age": [25, 32, 29, 41, 35, 28],
    "City": ["Delhi", "Lahore", "Delhi", "Karachi", "Lahore", "Delhi"],
    "Salary": [35000, 52000, 45000, 68000, 60000, 42000]
})

print("First 3 rows:")
display(df.head(3))
print("Shape:", df.shape)
print("Column names:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)

First 3 rows:

     Name  Age    City  Salary
0  Ayesha   25   Delhi   35000
1   Bilal   32  Lahore   52000
2    Chen   29   Delhi   45000

Shape: (6, 4)
Column names: ['Name', 'Age', 'City', 'Salary']

Data types:
Name      object
Age        int64
City      object
Salary     int64
dtype: object

2) Create a Series of 5 numbers with custom index labels ['a','b','c','d','e']. Print the value at label 'c', the values at positions 1 to 3, and the sum and mean of the Series.

In [2]:
# Create a Series with custom index labels
numbers = pd.Series([10, 20, 30, 40, 50], index=["a", "b", "c", "d", "e"])

print("Value at label 'c':", numbers.loc["c"])
print("Values at positions 1 to 3:")
print(numbers.iloc[1:4])  # iloc uses an exclusive stop index
print("Sum:", numbers.sum())
print("Mean:", numbers.mean())

Value at label 'c': 30
Values at positions 1 to 3:
b    20
c    30
d    40
dtype: int64
Sum: 150
Mean: 30.0

3) Create a CSV file (or use any CSV from the class data folder) and read it using pd.read_csv(). Display head(), tail(), info() and describe().

In [3]:
# Create a small CSV file, then read it with pd.read_csv()
csv_data = pd.DataFrame({
    "Name": ["Ayesha", "Bilal", "Chen", "Deepa", "Ethan", "Farah"],
    "Age": [25, 32, 29, 41, 35, 28],
    "City": ["Delhi", "Lahore", "Delhi", "Karachi", "Lahore", "Delhi"],
    "Salary": [35000, 52000, 45000, 68000, 60000, 42000]
})
csv_data.to_csv("employees.csv", index=False)

employees_from_csv = pd.read_csv("employees.csv")
print("Head:")
display(employees_from_csv.head())
print("Tail:")
display(employees_from_csv.tail())
print("Info:")
employees_from_csv.info()
print("\nDescribe:")
display(employees_from_csv.describe())

Head:

     Name  Age     City  Salary
0  Ayesha   25    Delhi   35000
1   Bilal   32   Lahore   52000
2    Chen   29    Delhi   45000
3   Deepa   41  Karachi   68000
4   Ethan   35   Lahore   60000

Tail:

    Name  Age     City  Salary
1  Bilal   32   Lahore   52000
2   Chen   29    Delhi   45000
3  Deepa   41  Karachi   68000
4  Ethan   35   Lahore   60000
5  Farah   28    Delhi   42000

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Salary  6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

Describe:

             Age        Salary
count   6.000000      6.000000
mean   31.666667  50333.333333
std     5.715476  12176.480061
min    25.000000  35000.000000
25%    28.250000  42750.000000
50%    30.500000  48500.000000
75%    34.250000  58000.000000
max    41.000000  68000.000000

4) From the DataFrame of Q1, select (a) only the Name and Salary columns, (b) rows where Age is greater than 30, (c) rows where City is 'Delhi' and Salary is above 40000.

In [4]:
# Select columns and filter rows from the Q1 DataFrame
print("(a) Name and Salary:")
display(df[["Name", "Salary"]])

print("(b) Employees whose Age is greater than 30:")
display(df[df["Age"] > 30])

print("(c) Employees in Delhi with Salary above 40000:")
display(df[(df["City"] == "Delhi") & (df["Salary"] > 40000)])

(a) Name and Salary:

     Name  Salary
0  Ayesha   35000
1   Bilal   52000
2    Chen   45000
3   Deepa   68000
4   Ethan   60000
5   Farah   42000

(b) Employees whose Age is greater than 30:

    Name  Age     City  Salary
1  Bilal   32   Lahore   52000
3  Deepa   41  Karachi   68000
4  Ethan   35   Lahore   60000

(c) Employees in Delhi with Salary above 40000:

    Name  Age   City  Salary
2   Chen   29  Delhi   45000
5  Farah   28  Delhi   42000

5) Use loc and iloc to (a) get the 2nd row, (b) get Name of the 4th employee, (c) get rows 1 to 3 with columns Name and City.

In [5]:
# loc uses labels; iloc uses integer positions
print("(a) Second row:")
display(df.iloc[1])

print("(b) Name of the 4th employee:")
print(df.iloc[3]["Name"])

print("(c) Rows 1 to 3 with Name and City (row positions 1, 2, 3):")
display(df.loc[1:3, ["Name", "City"]])

(a) Second row:

Name       Bilal
Age           32
City      Lahore
Salary     52000
Name: 1, dtype: object

(b) Name of the 4th employee:
Deepa
(c) Rows 1 to 3 with Name and City (row positions 1, 2, 3):

    Name     City
1  Bilal   Lahore
2   Chen    Delhi
3  Deepa  Karachi

6) Add a new column 'Bonus' that is 10% of Salary and a column 'Total' = Salary + Bonus. Then rename the column 'City' to 'Location' and drop the 'Bonus' column.

In [6]:
# Add Bonus and Total, rename City, then drop Bonus
df["Bonus"] = df["Salary"] * 0.10
df["Total"] = df["Salary"] + df["Bonus"]
df.rename(columns={"City": "Location"}, inplace=True)
df.drop(columns=["Bonus"], inplace=True)

print("Updated DataFrame:")
display(df)

Updated DataFrame:

     Name  Age Location  Salary    Total
0  Ayesha   25    Delhi   35000  38500.0
1   Bilal   32   Lahore   52000  57200.0
2    Chen   29    Delhi   45000  49500.0
3   Deepa   41  Karachi   68000  74800.0
4   Ethan   35   Lahore   60000  66000.0
5   Farah   28    Delhi   42000  46200.0

7) Create a DataFrame having some missing values (NaN). Find the count of missing values in each column, fill numeric NaNs with the column mean, and drop rows that still have missing values.

In [7]:
# Create a DataFrame with missing values
missing_df = pd.DataFrame({
    "Name": ["Ayesha", "Bilal", "Chen", "Deepa", "Ethan"],
    "Age": [25, None, 29, 41, None],
    "Salary": [35000, 52000, None, 68000, 60000],
    "City": ["Delhi", "Lahore", "Delhi", None, "Karachi"]
})

print("Missing values in each column:")
print(missing_df.isna().sum())

# Fill numeric missing values with each numeric column's mean
numeric_cols = missing_df.select_dtypes(include="number").columns
missing_df[numeric_cols] = missing_df[numeric_cols].fillna(missing_df[numeric_cols].mean())

# Drop any rows that still contain missing values (for example, missing City)
clean_df = missing_df.dropna()

print("\nDataFrame after filling numeric NaNs and dropping remaining missing rows:")
display(clean_df)

Missing values in each column:
Name      0
Age       2
Salary    1
City      1
dtype: int64

DataFrame after filling numeric NaNs and dropping remaining missing rows:

     Name        Age   Salary     City
0  Ayesha  25.000000  35000.0    Delhi
1   Bilal  31.666667  52000.0   Lahore
2    Chen  29.000000  53750.0    Delhi
4   Ethan  31.666667  60000.0  Karachi

8) Sort the DataFrame by Salary in descending order, and then by Age in ascending order. Also print the top 3 highest-paid employees using nlargest().

In [8]:
# Sort by Salary descending, then Age ascending
sorted_df = df.sort_values(by=["Salary", "Age"], ascending=[False, True])
print("Sorted by Salary (descending), then Age (ascending):")
display(sorted_df)

print("Top 3 highest-paid employees:")
display(df.nlargest(3, "Salary"))

Sorted by Salary (descending), then Age (ascending):

     Name  Age Location  Salary    Total
3   Deepa   41  Karachi   68000  74800.0
4   Ethan   35   Lahore   60000  66000.0
1   Bilal   32   Lahore   52000  57200.0
2    Chen   29    Delhi   45000  49500.0
5   Farah   28    Delhi   42000  46200.0
0  Ayesha   25    Delhi   35000  38500.0

Top 3 highest-paid employees:

    Name  Age Location  Salary    Total
3  Deepa   41  Karachi   68000  74800.0
4  Ethan   35   Lahore   60000  66000.0
1  Bilal   32   Lahore   52000  57200.0

9) Using groupby, find the average salary per City, the number of employees per City, and the maximum salary per City. Show the result using agg() with multiple functions.

In [9]:
# Group by City and calculate multiple statistics for Salary
city_summary = df.groupby("Location").agg(
    Average_Salary=("Salary", "mean"),
    Employee_Count=("Name", "count"),
    Maximum_Salary=("Salary", "max")
)
print("Salary summary by City:")
display(city_summary)

Salary summary by City:

          Average_Salary  Employee_Count  Maximum_Salary
Location
Delhi       40666.666667               3           45000
Karachi     68000.000000               1           68000
Lahore      56000.000000               2           60000

10) Create two DataFrames (employees and departments) with a common column 'DeptID'. Merge them using inner and left joins, then concatenate two DataFrames of the same structure using pd.concat() and remove duplicate rows.

In [10]:
# Create employees and departments DataFrames with a common DeptID
employees = pd.DataFrame({
    "EmployeeID": [1, 2, 3, 4],
    "Name": ["Ayesha", "Bilal", "Chen", "Deepa"],
    "DeptID": [10, 20, 10, 30]
})
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "Department": ["Analytics", "Marketing", "Finance"]
})

print("Inner join (only matching DeptID values):")
display(pd.merge(employees, departments, on="DeptID", how="inner"))

print("Left join (all employees retained):")
display(pd.merge(employees, departments, on="DeptID", how="left"))

# Concatenate two DataFrames with the same structure, then remove duplicates
employees_part1 = employees.iloc[:3]
employees_part2 = pd.concat([employees.iloc[2:], employees.iloc[[0]]], ignore_index=True)
combined = pd.concat([employees_part1, employees_part2], ignore_index=True)
print("Concatenated DataFrame after removing duplicate rows:")
display(combined.drop_duplicates().reset_index(drop=True))

Inner join (only matching DeptID values):

   EmployeeID    Name  DeptID Department
0           1  Ayesha      10  Analytics
1           2   Bilal      20  Marketing
2           3    Chen      10  Analytics

Left join (all employees retained):

   EmployeeID    Name  DeptID Department
0           1  Ayesha      10  Analytics
1           2   Bilal      20  Marketing
2           3    Chen      10  Analytics
3           4   Deepa      30        NaN

Concatenated DataFrame after removing duplicate rows:

   EmployeeID    Name  DeptID
0           1  Ayesha      10
1           2   Bilal      20
2           3    Chen      10
3           4   Deepa      30