In [3]:
import pandas as pd

In [ ]:
# pip install pandas

# Series
- One Dimensional Array

In [4]:
revenue = pd.Series([123,456,7889,986])
print(revenue)

0     123
1     456
2    7889
3     986
dtype: int64

In [ ]:
revenue = pd.Series([123,456,7889,986],
            index = ["jan","feb","march","april"])  # one dimensional array
print(revenue)

jan       123
feb       456
march    7889
april     986
dtype: int64

In [9]:
print(revenue["jan"])

123

# DataFrames
- 2d with label raws ans column

In [10]:
data = {
    "name":       ["Alice", "Bob", "Carol", "David", "Eve"],
    "department": ["Engineering", "Finance", "Engineering", "HR", "Finance"],
    "salary":     [85000, 72000, 91000, 65000, 78000],
    "active":     [True, True, False, True, True]
}

df = pd.DataFrame(data)
print(df)

    name   department  salary  active
0  Alice  Engineering   85000    True
1    Bob      Finance   72000    True
2  Carol  Engineering   91000   False
3  David           HR   65000    True
4    Eve      Finance   78000    True

# Read CSV File

In [4]:
df = pd.read_csv('employees_data.csv')

In [5]:
print(df)

     name department  salary active
0    Ayan        ENG  2000.0    yes
1   Nasir        FIN  5000.0    yes
2  Faizan         DE  8000.0    yes
3   Irfan         DA     NaN     no
4    ayaz         DA     NaN     no

In [ ]:
# data hai kitna bara ? what's size of data   
# data type kiya hian ?   
# statistics (mean, median, mode)  
# Aggreated values (max, min, avg)

In [ ]:
print(df.shape)  # Rows , Column

(5, 4)

In [7]:
print(df.dtypes)

name              str
department        str
salary        float64
active            str
dtype: object

In [10]:
print(df.columns)

Index(['name', 'department', 'salary', 'active'], dtype='str')

# Meta data

- A data with in data is called metadata

In [ ]:
df.head(3)  # By Default returns first 5 rows

     name department  salary active
0    Ayan        ENG  2000.0    yes
1   Nasir        FIN  5000.0    yes
2  Faizan         DE  8000.0    yes

In [11]:
df.tail()  # By Default returns last 5 rows

     name department  salary active
0    Ayan        ENG  2000.0    yes
1   Nasir        FIN  5000.0    yes
2  Faizan         DE  8000.0    yes
3   Irfan         DA     NaN     no
4    ayaz         DA     NaN     no

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   department  5 non-null      str
 2   salary      3 non-null      float64
 3   active      5 non-null      str
dtypes: float64(1), str(3)
memory usage: 292.0 bytes

In [13]:
df.describe()

       salary
count     3.0
mean   5000.0
std    3000.0
min    2000.0
25%    3500.0
50%    5000.0
75%    6500.0
max    8000.0